name: tests
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.12"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install pip packages
        run: |
          pip install uv
          uv pip install --system -r tests/requirements.txt .[dev]

      - name: Run tests with pytest
        run: pytest --cov=ts_workflow_examples --cov-report=xml

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v4
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./coverage.xml  # Adjust path to your coverage report if needed
#          flags: unittests
#          name: codecov-ubuntu  # Optional name for the upload
#          fail_ci_if_error: true
#          directory: ./  # Adjust if the coverage file is in a different directory
#          override_branch: ${{ github.head_ref || github.ref_name }}
#          override_commit: ${{ github.sha }}
#          override_pr: ${{ github.event.number }}
#          repository: ts-workflow-examples/ts_workflow_examples
